[project]
name = "pandas-60"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "catppuccin>=2.5.0",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
]
